---

language: python
python: 2.7

install:
    - pip install ansible
    - pip install yamllint
    - pip install ansible-lint

script:
    - cd tests && ansible-playbook test.yml -i inventory --syntax-check
    - ansible-lint test.yml
