- hosts: nodes
  gather_facts: false
  tasks:
    - name: print hostname from cache
      debug:
        var: my_hostname
      when: my_hostname is defined

    - name: hostname
      command: hostname
      register: hostname_result
      when: my_hostname is not defined

    - name: cache hostname
      set_fact:
        my_hostname: "{{ hostname_result.stdout }}"
        cacheable: true
      when: my_hostname is not defined
